FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_sentence.txt .
RUN pip install --no-cache-dir -r requirements_sentence.txt

COPY _complete_sentence_transformer_example.ipynb /app/
COPY _split_train_test_data.ipynb /app/
COPY backups/backup_16_39_09_02_2025.json /app/backups/
COPY __statistic_roc_boxplot.ipynb /app/

COPY texts/ /app/texts/
COPY texts_v2/ /app/texts_v2/
COPY training_splits/ /app/training_splits/
COPY test_splits/ /app/test_splits/
COPY evaluation_area /app/evaluation_area/

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=5555", "--no-browser", "--allow-root"]

# to build => docker build -f dockerfile_sentence -t bertdoc_sentence:latest .
# to start => docker run -p 5555:5555 bertdoc_sentence:latest
# look for a token for jupyter e.g. =>  http://127.0.0.1:7777/tree?token=2df1de0b1668d6811b09a56dedd70232953bc223b6c5764e
# run _complete_sentence_transformer_example.ipynb